// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbVzUwHm86zvDhX5upUmIbNQARaGgkTGM',
    appId: '1:542954239424:web:496ea304de517982414425',
    messagingSenderId: '542954239424',
    projectId: 'markit-53d97',
    authDomain: 'markit-53d97.firebaseapp.com',
    storageBucket: 'markit-53d97.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzXh7CS4JoKLTiC7X5O2fTxTIg8JKXJ0o',
    appId: '1:542954239424:android:7edd94a3a53b5fdb414425',
    messagingSenderId: '542954239424',
    projectId: 'markit-53d97',
    storageBucket: 'markit-53d97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPwyGp7vKqSFcUWY2trBAi3aOxBMkcsfA',
    appId: '1:542954239424:ios:92911fd585d8627f414425',
    messagingSenderId: '542954239424',
    projectId: 'markit-53d97',
    storageBucket: 'markit-53d97.appspot.com',
    iosBundleId: 'com.example.markIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPwyGp7vKqSFcUWY2trBAi3aOxBMkcsfA',
    appId: '1:542954239424:ios:329854f9f6f17504414425',
    messagingSenderId: '542954239424',
    projectId: 'markit-53d97',
    storageBucket: 'markit-53d97.appspot.com',
    iosBundleId: 'com.example.markIt.RunnerTests',
  );
}
